_homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }
_log_in:
    path:     /login
    defaults: { _controller: AppBundle:Access:LogIn }

_logout:
    path:     /logout
    defaults: { _controller: AppBundle:Access:Logout }
