_login:
    path:     /login
    defaults: { _controller: AppBundle:Access:Login }
    
_signup:
    path:     /signup
    defaults: { _controller: AppBundle:Access:Signup }
_logout:
    path:     /logout

_main:
    path:     /
    defaults: { _controller: AppBundle:Main:Main }
    
##Resource Asyncronous Loading
RAL:
    path:     /RAL/{request}
    defaults: { _controller: AppBundle:RAL:index }
    requirements:
        request: .+
##AJAX PAGES
_start:
    path:     /Main
    defaults: { _controller: AppBundle:Main:Start }
_files:
    path:     /Drive
    defaults: { _controller: AppBundle:Main:Drive }
_shared:
    path:     /Compartidos
    defaults: { _controller: AppBundle:Main:Shared }
_trash:
    path:     /Papelera
    defaults: { _controller: AppBundle:Main:Trash }
_my_profile:
    path:     /Perfil
    defaults: { _controller: AppBundle:Main:Profile }
_edit_profile:
    path:     /Editar/Perfil
    defaults: { _controller: AppBundle:Main:EditProfile }
_profile:
    path:     /Perfil/{username}
    defaults: { _controller: AppBundle:Main:Profile }
    
##API METHODS
_submit:
    path:     /API/Submit
    defaults: { _controller: AppBundle:Api:Submit, item: ~ }
    
_mark:
    path:     /API/Mark/{item}
    defaults: { _controller: AppBundle:Api:Mark, item: ~ }

_delete:
    path:     /API/Delete/{item}
    defaults: { _controller: AppBundle:Api:Delete, item: ~ }

_drop:
    path:     /API/Drop/{item}
    defaults: { _controller: AppBundle:Api:Drop, item: ~ }

_share:
    path:     /API/Share/{item}
    defaults: { _controller: AppBundle:Api:Share, item: ~ }

_recover:
    path:     /API/Recover/{item}
    defaults: { _controller: AppBundle:Api:Recover, item: ~ }
