AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: '{{ value }} esta en uso'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [username]
            message: 'Esta cuenta ya existe'
    properties:
        username:
            - NotBlank: {message: "El nombre de usuario no puede estar vacio."}
        email:
            - Email:
                message: 'El correo {{ value }} no es valido.'
                checkMX: true