AppBundle\Entity\Folder:
    type: entity
    table: Folders
    repositoryClass: AppBundle\Repository\FolderRepository
    manyToOne:
        owner:
            targetEntity: User
            joinColumn:
                name: Owner
                referencedColumnName: Username
        entity:
            targetEntity: Entity
            joinColumn:
                name: Entity
                referencedColumnName: Entity
        parent:
            targetEntity: Folder
            inversedBy: childs
            joinColumn:
                name: Parent
                referencedColumnName: FolderID
    oneToMany:
        childs:
            targetEntity: Folder
            mappedBy: parent
    id:
        folderID:
            type: guid
            id: true
            column: FolderID
            generator:
                strategy: UUID
    fields:
        name:
            type: string
            length: 255
            column: Name
        creationDate:
            type: datetime
            column: CreationDate
        lastModifiedDate:
            type: datetime
            column: LastModifiedDate
        lastAccessDate:
            type: datetime
            column: LastAccessDate
    lifecycleCallbacks: {  }
