AppBundle\Entity\Permission:
    type: entity
    table: Permissions
    repositoryClass: AppBundle\Repository\PermissionRepository
    manyToOne:
        entity:
            targetEntity: Entity
            joinColumn:
                name: Entity
                referencedColumnName: Entity
        user:
            targetEntity: User
            joinColumn:
                name: User
                referencedColumnName: Username
    id:
        entityID:
            type: guid
            id: true
        entity:
            associationKey: true
        user:
            associationKey: true
    fields:
        canRead:
            type: boolean
            column: CanRead
        canWrite:
            type: boolean
            column: CanWrite
    lifecycleCallbacks: {  }
