AppBundle\Entity\Trash:
    type: entity
    table: TrashBin
    repositoryClass: AppBundle\Repository\TrashRepository
    manyToOne:
        entity:
            targetEntity: Entity
            joinColumn:
                name: Entity
                referencedColumnName: Entity
        deletedBy:
            targetEntity: User
            joinColumn:
                name: DeletedBy
                referencedColumnName: Username
    id:
        trashID:
            type: guid
            id: true
            column: TrashID
            generator:
                strategy: UUID
    fields:
        entityID:
            type: guid
            column: EntityID
        liveUntil:
            type: datetime
            column: LiveUntil
        deletedOn:
            type: datetime
            column: DeletedOn
    lifecycleCallbacks: {  }
