AppBundle\Entity\Trash:
    type: entity
    table: TrashBin
    repositoryClass: AppBundle\Repository\TrashRepository
    manyToOne:
        entity:
            targetEntity: Entity
            joinColumn:
                name: Entity
                referencedColumnName: Entity
        deletedBy:
            targetEntity: User
            joinColumn:
                name: DeletedBy
                referencedColumnName: Username
    id:
        entityID:
            type: guid
            id: true
            column: EntityID
        entity:
            associationKey: true
    fields:
        liveUntil:
            type: datetime
            column: LiveUntil
        deletedOn:
            type: datetime
            column: DeletedOn
    lifecycleCallbacks: {  }
