AppBundle\Entity\User:
    type: entity
    table: Users
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        username:
            type: string
            id: true
    fields:
        password:
            type: string
            length: '80'
    lifecycleCallbacks: {  }
